test_lab1:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab1
test_lab2:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab2
test_lab3:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab3
test_lab4:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab4
test_lab5_part1:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab5-1
test_lab5_part2:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab5-2
test_lab5:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab5
test_lab6:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab6
test_lab6_llref:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab6-llref