test_lab1:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab1
test_lab2:
  image: ipadsse302/tigerlabs_env:2.0.0
  tags:
    - r743
  stage: test
  script:
    - make gradelab2